package com.zcbspay.platform.member.individual.pojo;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
// Generated 2016-8-18 17:46:50 by Hibernate Tools 4.0.0
import java.util.Date;

/**
 * TMemberApply generated by hbm2java
 */
@Entity
@Table(name = "T_MEMBER_APPLY")
public class PojoMemberApply implements Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -935102899779534028L;
	private long selfId;
	private long memId;
	private String memberId;
	private String instiCode;
	private String memberName;
	private String loginName;
	private String pwd;
	private String payPwd;
	private String realnameLv;
	private String phone;
	private String email;
	private String memberType;
	private String status;
	private String registerIdent;
	private Date lockTime;
	private Date inTime;
	private Date upTime;

	public PojoMemberApply() {
	}

	public PojoMemberApply(long selfId, long memId, String memberId, String pwd,
			String memberType, String status, String registerIdent) {
		this.selfId = selfId;
		this.memId = memId;
		this.memberId = memberId;
		this.pwd = pwd;
		this.memberType = memberType;
		this.status = status;
		this.registerIdent = registerIdent;
	}

	public PojoMemberApply(long selfId, long memId, String memberId,
			String instiCode, String memberName, String loginName, String pwd,
			String payPwd, String realnameLv, String phone, String email,
			String memberType, String status, String registerIdent,
			Date lockTime, Date inTime, Date upTime) {
		this.selfId = selfId;
		this.memId = memId;
		this.memberId = memberId;
		this.instiCode = instiCode;
		this.memberName = memberName;
		this.loginName = loginName;
		this.pwd = pwd;
		this.payPwd = payPwd;
		this.realnameLv = realnameLv;
		this.phone = phone;
		this.email = email;
		this.memberType = memberType;
		this.status = status;
		this.registerIdent = registerIdent;
		this.lockTime = lockTime;
		this.inTime = inTime;
		this.upTime = upTime;
	}
	/*@GenericGenerator(name = "id_gen", strategy = "enhanced-table", parameters = {
            @Parameter(name = "table_name", value = "T_C_PRIMAY_KEY"),
            @Parameter(name = "value_column_name", value = "NEXT_ID"),
            @Parameter(name = "segment_column_name", value = "KEY_NAME"),
            @Parameter(name = "segment_value", value = "FOR_APPLY_ID"),
            @Parameter(name = "increment_size", value = "1"),
            @Parameter(name = "optimizer", value = "pooled-lo") })*/
    
//	@GeneratedValue(generator = "id_gen")
	@Id
	@Column(name = "SELF_ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getSelfId() {
		return this.selfId;
	}

	public void setSelfId(long selfId) {
		this.selfId = selfId;
	}
	
	/*@GenericGenerator(name = "id_gen2", strategy = "enhanced-table", parameters = {
            @Parameter(name = "table_name", value = "T_C_PRIMAY_KEY"),
            @Parameter(name = "value_column_name", value = "NEXT_ID"),
            @Parameter(name = "segment_column_name", value = "KEY_NAME"),
            @Parameter(name = "segment_value", value = "MEMBER_ID"),
            @Parameter(name = "increment_size", value = "1"),
            @Parameter(name = "optimizer", value = "pooled-lo") })*/
//	@GeneratedValue(generator = "id_gen2")
	@Column(name = "MEM_ID", nullable = false, precision = 15, scale = 0)
	public long getMemId() {
		return this.memId;
	}

	public void setMemId(long memId) {
		this.memId = memId;
	}

	@Column(name = "MEMBER_ID", nullable = false, length = 15)
	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	@Column(name = "INSTI_CODE", length = 15)
	public String getInstiCode() {
		return this.instiCode;
	}

	public void setInstiCode(String instiCode) {
		this.instiCode = instiCode;
	}

	@Column(name = "MEMBER_NAME", length = 64)
	public String getMemberName() {
		return this.memberName;
	}

	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}

	@Column(name = "LOGIN_NAME", length = 64)
	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	@Column(name = "PWD", nullable = false, length = 32)
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Column(name = "PAY_PWD", length = 32)
	public String getPayPwd() {
		return this.payPwd;
	}

	public void setPayPwd(String payPwd) {
		this.payPwd = payPwd;
	}

	@Column(name = "REALNAME_LV", length = 2)
	public String getRealnameLv() {
		return this.realnameLv;
	}

	public void setRealnameLv(String realnameLv) {
		this.realnameLv = realnameLv;
	}

	@Column(name = "PHONE", length = 32)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "EMAIL", length = 32)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "MEMBER_TYPE", nullable = false, length = 2)
	public String getMemberType() {
		return this.memberType;
	}

	public void setMemberType(String memberType) {
		this.memberType = memberType;
	}

	@Column(name = "STATUS", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "REGISTER_IDENT", nullable = false, length = 2)
	public String getRegisterIdent() {
		return this.registerIdent;
	}

	public void setRegisterIdent(String registerIdent) {
		this.registerIdent = registerIdent;
	}

//	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LOCK_TIME", length = 7)
	public Date getLockTime() {
		return this.lockTime;
	}

	public void setLockTime(Date lockTime) {
		this.lockTime = lockTime;
	}

//	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IN_TIME", length = 7)
	public Date getInTime() {
		return this.inTime;
	}

	public void setInTime(Date inTime) {
		this.inTime = inTime;
	}

//	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UP_TIME", length = 7)
	public Date getUpTime() {
		return this.upTime;
	}

	public void setUpTime(Date upTime) {
		this.upTime = upTime;
	}

}
