package com.zcbspay.platform.member.merchant.pojo;

// Generated 2016-8-18 17:46:50 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TEnterpriseDetaApply generated by hbm2java
 */
@Entity
@Table(name = "T_ENTERPRISE_DETA_APPLY")
public class PojoEnterpriseDetaApply implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 9188709266938011350L;
	private long selfId;
	private long enterpriseId;
	private String memberId;
	private String enterpriseName;
	private Long coopInstiId;
	private String mcc;
	private String mccList;
	private Long enterpriseInsti;
	private Long province;
	private Long city;
	private Long street;
	private String zoneCode;
	private String postCode;
	private String address;
	private String cellPhoneNo;
	private String email;
	private String website;
	private String cardType;
	private String taxNo;
	private String licenceNo;
	private String orgCode;
	private String corporation;
	private String corpNo;
	private String corpFile;
	private String corpFileOpp;
	private String taxFile;
	private String licenceFile;
	private String orgCodeFile;
	private String contact;
	private String contPhone;
	private String contTitle;
	private String contEmail;
	private String contAddress;
	private String contPost;
	private String custFrom;
	private String custMgr;
	private String custMgrDept;
	private Short isDelegation;
	private String signatory;
	private String signCertNo;
	private String signCertFile;
	private String signCertFileOpp;
	private String status;
	private Date firstTime;
	private Long inUser;
	private Date inTime;
	private Long stexaUser;
	private Date stexaTime;
	private String stexaOpt;
	private Long cvlexaUser;
	private Date cvlexaTime;
	private String cvlexaOpt;
	private String notes;
	private String remarks;

	public PojoEnterpriseDetaApply() {
	}

	public PojoEnterpriseDetaApply(long selfId, long enterpriseId) {
		this.selfId = selfId;
		this.enterpriseId = enterpriseId;
	}

	public PojoEnterpriseDetaApply(long selfId, long enterpriseId, String memberId, String enterpriseName,
			Long coopInstiId, String mcc, String mccList, Long enterpriseInsti, Long province, Long city, Long street,
			String zoneCode, String postCode, String address, String cellPhoneNo, String email, String website,
			String cardType, String taxNo, String licenceNo, String orgCode, String corporation, String corpNo,
			String corpFile, String corpFileOpp, String taxFile, String licenceFile, String orgCodeFile, String contact,
			String contPhone, String contTitle, String contEmail, String contAddress, String contPost, String custFrom,
			String custMgr, String custMgrDept, Short isDelegation, String signatory, String signCertNo,
			String signCertFile, String signCertFileOpp, String status, Date firstTime, Long inUser, Date inTime,
			Long stexaUser, Date stexaTime, String stexaOpt, Long cvlexaUser, Date cvlexaTime, String cvlexaOpt,
			String notes, String remarks) {
		this.selfId = selfId;
		this.enterpriseId = enterpriseId;
		this.memberId = memberId;
		this.enterpriseName = enterpriseName;
		this.coopInstiId = coopInstiId;
		this.mcc = mcc;
		this.mccList = mccList;
		this.enterpriseInsti = enterpriseInsti;
		this.province = province;
		this.city = city;
		this.street = street;
		this.zoneCode = zoneCode;
		this.postCode = postCode;
		this.address = address;
		this.cellPhoneNo = cellPhoneNo;
		this.email = email;
		this.website = website;
		this.cardType = cardType;
		this.taxNo = taxNo;
		this.licenceNo = licenceNo;
		this.orgCode = orgCode;
		this.corporation = corporation;
		this.corpNo = corpNo;
		this.corpFile = corpFile;
		this.corpFileOpp = corpFileOpp;
		this.taxFile = taxFile;
		this.licenceFile = licenceFile;
		this.orgCodeFile = orgCodeFile;
		this.contact = contact;
		this.contPhone = contPhone;
		this.contTitle = contTitle;
		this.contEmail = contEmail;
		this.contAddress = contAddress;
		this.contPost = contPost;
		this.custFrom = custFrom;
		this.custMgr = custMgr;
		this.custMgrDept = custMgrDept;
		this.isDelegation = isDelegation;
		this.signatory = signatory;
		this.signCertNo = signCertNo;
		this.signCertFile = signCertFile;
		this.signCertFileOpp = signCertFileOpp;
		this.status = status;
		this.firstTime = firstTime;
		this.inUser = inUser;
		this.inTime = inTime;
		this.stexaUser = stexaUser;
		this.stexaTime = stexaTime;
		this.stexaOpt = stexaOpt;
		this.cvlexaUser = cvlexaUser;
		this.cvlexaTime = cvlexaTime;
		this.cvlexaOpt = cvlexaOpt;
		this.notes = notes;
		this.remarks = remarks;
	}

	
	@Id
	@Column(name = "SELF_ID", unique = true, nullable = false, precision = 15, scale = 0)
	public long getSelfId() {
		return this.selfId;
	}

	public void setSelfId(long selfId) {
		this.selfId = selfId;
	}

	@Column(name = "ENTERPRISE_ID", nullable = false, precision = 15, scale = 0)
	public long getEnterpriseId() {
		return this.enterpriseId;
	}

	public void setEnterpriseId(long enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	@Column(name = "MEMBER_ID", length = 15)
	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	@Column(name = "ENTERPRISE_NAME", length = 128)
	public String getEnterpriseName() {
		return this.enterpriseName;
	}

	public void setEnterpriseName(String enterpriseName) {
		this.enterpriseName = enterpriseName;
	}

	@Column(name = "COOP_INSTI_ID", precision = 11, scale = 0)
	public Long getCoopInstiId() {
		return this.coopInstiId;
	}

	public void setCoopInstiId(Long coopInstiId) {
		this.coopInstiId = coopInstiId;
	}

	@Column(name = "MCC", length = 4)
	public String getMcc() {
		return this.mcc;
	}

	public void setMcc(String mcc) {
		this.mcc = mcc;
	}

	@Column(name = "MCC_LIST", length = 4)
	public String getMccList() {
		return this.mccList;
	}

	public void setMccList(String mccList) {
		this.mccList = mccList;
	}

	@Column(name = "ENTERPRISE_INSTI", precision = 10, scale = 0)
	public Long getEnterpriseInsti() {
		return this.enterpriseInsti;
	}

	public void setEnterpriseInsti(Long enterpriseInsti) {
		this.enterpriseInsti = enterpriseInsti;
	}

	@Column(name = "PROVINCE", precision = 10, scale = 0)
	public Long getProvince() {
		return this.province;
	}

	public void setProvince(Long province) {
		this.province = province;
	}

	@Column(name = "CITY", precision = 10, scale = 0)
	public Long getCity() {
		return this.city;
	}

	public void setCity(Long city) {
		this.city = city;
	}

	@Column(name = "STREET", precision = 10, scale = 0)
	public Long getStreet() {
		return this.street;
	}

	public void setStreet(Long street) {
		this.street = street;
	}

	@Column(name = "ZONE_CODE", length = 8)
	public String getZoneCode() {
		return this.zoneCode;
	}

	public void setZoneCode(String zoneCode) {
		this.zoneCode = zoneCode;
	}

	@Column(name = "POST_CODE", length = 8)
	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	@Column(name = "ADDRESS", length = 256)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "CELL_PHONE_NO", length = 11)
	public String getCellPhoneNo() {
		return this.cellPhoneNo;
	}

	public void setCellPhoneNo(String cellPhoneNo) {
		this.cellPhoneNo = cellPhoneNo;
	}

	@Column(name = "EMAIL", length = 32)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "WEBSITE", length = 128)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "CARD_TYPE", length = 2)
	public String getCardType() {
		return this.cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	@Column(name = "TAX_NO", length = 32)
	public String getTaxNo() {
		return this.taxNo;
	}

	public void setTaxNo(String taxNo) {
		this.taxNo = taxNo;
	}

	@Column(name = "LICENCE_NO", length = 32)
	public String getLicenceNo() {
		return this.licenceNo;
	}

	public void setLicenceNo(String licenceNo) {
		this.licenceNo = licenceNo;
	}

	@Column(name = "ORG_CODE", length = 10)
	public String getOrgCode() {
		return this.orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	@Column(name = "CORPORATION", length = 32)
	public String getCorporation() {
		return this.corporation;
	}

	public void setCorporation(String corporation) {
		this.corporation = corporation;
	}

	@Column(name = "CORP_NO", length = 18)
	public String getCorpNo() {
		return this.corpNo;
	}

	public void setCorpNo(String corpNo) {
		this.corpNo = corpNo;
	}

	@Column(name = "CORP_FILE", length = 128)
	public String getCorpFile() {
		return this.corpFile;
	}

	public void setCorpFile(String corpFile) {
		this.corpFile = corpFile;
	}

	@Column(name = "CORP_FILE_OPP", length = 128)
	public String getCorpFileOpp() {
		return this.corpFileOpp;
	}

	public void setCorpFileOpp(String corpFileOpp) {
		this.corpFileOpp = corpFileOpp;
	}

	@Column(name = "TAX_FILE", length = 128)
	public String getTaxFile() {
		return this.taxFile;
	}

	public void setTaxFile(String taxFile) {
		this.taxFile = taxFile;
	}

	@Column(name = "LICENCE_FILE", length = 128)
	public String getLicenceFile() {
		return this.licenceFile;
	}

	public void setLicenceFile(String licenceFile) {
		this.licenceFile = licenceFile;
	}

	@Column(name = "ORG_CODE_FILE", length = 128)
	public String getOrgCodeFile() {
		return this.orgCodeFile;
	}

	public void setOrgCodeFile(String orgCodeFile) {
		this.orgCodeFile = orgCodeFile;
	}

	@Column(name = "CONTACT", length = 32)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "CONT_PHONE", length = 32)
	public String getContPhone() {
		return this.contPhone;
	}

	public void setContPhone(String contPhone) {
		this.contPhone = contPhone;
	}

	@Column(name = "CONT_TITLE", length = 32)
	public String getContTitle() {
		return this.contTitle;
	}

	public void setContTitle(String contTitle) {
		this.contTitle = contTitle;
	}

	@Column(name = "CONT_EMAIL", length = 32)
	public String getContEmail() {
		return this.contEmail;
	}

	public void setContEmail(String contEmail) {
		this.contEmail = contEmail;
	}

	@Column(name = "CONT_ADDRESS", length = 256)
	public String getContAddress() {
		return this.contAddress;
	}

	public void setContAddress(String contAddress) {
		this.contAddress = contAddress;
	}

	@Column(name = "CONT_POST", length = 6)
	public String getContPost() {
		return this.contPost;
	}

	public void setContPost(String contPost) {
		this.contPost = contPost;
	}

	@Column(name = "CUST_FROM", length = 64)
	public String getCustFrom() {
		return this.custFrom;
	}

	public void setCustFrom(String custFrom) {
		this.custFrom = custFrom;
	}

	@Column(name = "CUST_MGR", length = 32)
	public String getCustMgr() {
		return this.custMgr;
	}

	public void setCustMgr(String custMgr) {
		this.custMgr = custMgr;
	}

	@Column(name = "CUST_MGR_DEPT", length = 64)
	public String getCustMgrDept() {
		return this.custMgrDept;
	}

	public void setCustMgrDept(String custMgrDept) {
		this.custMgrDept = custMgrDept;
	}

	@Column(name = "IS_DELEGATION", precision = 3, scale = 0)
	public Short getIsDelegation() {
		return this.isDelegation;
	}

	public void setIsDelegation(Short isDelegation) {
		this.isDelegation = isDelegation;
	}

	@Column(name = "SIGNATORY", length = 18)
	public String getSignatory() {
		return this.signatory;
	}

	public void setSignatory(String signatory) {
		this.signatory = signatory;
	}

	@Column(name = "SIGN_CERT_NO", length = 18)
	public String getSignCertNo() {
		return this.signCertNo;
	}

	public void setSignCertNo(String signCertNo) {
		this.signCertNo = signCertNo;
	}

	@Column(name = "SIGN_CERT_FILE", length = 128)
	public String getSignCertFile() {
		return this.signCertFile;
	}

	public void setSignCertFile(String signCertFile) {
		this.signCertFile = signCertFile;
	}

	@Column(name = "SIGN_CERT_FILE_OPP", length = 128)
	public String getSignCertFileOpp() {
		return this.signCertFileOpp;
	}

	public void setSignCertFileOpp(String signCertFileOpp) {
		this.signCertFileOpp = signCertFileOpp;
	}

	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FIRST_TIME", length = 7)
	public Date getFirstTime() {
		return this.firstTime;
	}

	public void setFirstTime(Date firstTime) {
		this.firstTime = firstTime;
	}

	@Column(name = "IN_USER", precision = 10, scale = 0)
	public Long getInUser() {
		return this.inUser;
	}

	public void setInUser(Long inUser) {
		this.inUser = inUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IN_TIME", length = 7)
	public Date getInTime() {
		return this.inTime;
	}

	public void setInTime(Date inTime) {
		this.inTime = inTime;
	}

	@Column(name = "STEXA_USER", precision = 10, scale = 0)
	public Long getStexaUser() {
		return this.stexaUser;
	}

	public void setStexaUser(Long stexaUser) {
		this.stexaUser = stexaUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STEXA_TIME", length = 7)
	public Date getStexaTime() {
		return this.stexaTime;
	}

	public void setStexaTime(Date stexaTime) {
		this.stexaTime = stexaTime;
	}

	@Column(name = "STEXA_OPT", length = 256)
	public String getStexaOpt() {
		return this.stexaOpt;
	}

	public void setStexaOpt(String stexaOpt) {
		this.stexaOpt = stexaOpt;
	}

	@Column(name = "CVLEXA_USER", precision = 10, scale = 0)
	public Long getCvlexaUser() {
		return this.cvlexaUser;
	}

	public void setCvlexaUser(Long cvlexaUser) {
		this.cvlexaUser = cvlexaUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CVLEXA_TIME", length = 7)
	public Date getCvlexaTime() {
		return this.cvlexaTime;
	}

	public void setCvlexaTime(Date cvlexaTime) {
		this.cvlexaTime = cvlexaTime;
	}

	@Column(name = "CVLEXA_OPT", length = 256)
	public String getCvlexaOpt() {
		return this.cvlexaOpt;
	}

	public void setCvlexaOpt(String cvlexaOpt) {
		this.cvlexaOpt = cvlexaOpt;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
